# Change baseurl before deploy
baseurl = "https://bdelafaire.github.io/autour-de-moi/"
languageCode = "en-us"
paginate = 5
title = "Journal de bord"

timeout = "1000s"


####################################
####### MULTILINGUAL SUPPORT #######
####################################
defaultContentLanguage = 'fr'
defaultContentLanguageInSubdir = true
[languages]
  [languages.en]
    contentDir = 'content/en'
    disabled = false
    languageCode = 'en-US'
    languageDirection = 'ltr'
    languageName = 'English'
    title = 'Autour de moi'
    weight = 2
    [languages.en.params]
      subtitle = 'All about me and my trip'
  [languages.fr]
    contentDir = 'content/fr'
    disabled = false
    languageCode = 'fr-FR'
    languageDirection = 'ltr'
    languageName = 'Français'
    title = 'Autour de moi'
    weight = 2
    [languages.fr.params]
      subtitle = 'Tout sur moi et mes voyages'
####################################
####################################
####################################

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
# This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage = false

# Change it to your Disqus shortname before using
disqusShortname = "hugo-theme-stack"

# GA
googleAnalytics = "G-825XE1B6S7"
